# Generated by Django 2.2.1 on 2019-05-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnament_name', models.CharField(max_length=64)),
                ('turnament_place', models.CharField(max_length=64)),
                ('turnament_description', models.CharField(max_length=255)),
                ('turnament_date', models.DateTimeField(null=True)),
                ('turnament_price', models.IntegerField(null=True)),
                ('turnament_grade', models.IntegerField(choices=[(1, 'Bardzo Slaby'), (2, 'Slaby'), (3, 'Sredni'), (4, 'Dobry'), (5, 'Bardzo Dobry')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('user_password', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=64)),
                ('user_description', models.CharField(max_length=120)),
            ],
        ),
    ]
