# Generated by Django 2.2.1 on 2019-05-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excercise', '0002_auto_20190515_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnament',
            old_name='turnament_date_end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='turnament',
            old_name='turnament_date_start',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='turnament',
            old_name='turnament_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='turnament',
            old_name='turnament_grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='turnament',
            old_name='turnament_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='turnament',
            old_name='turnament_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='turnament',
            old_name='turnament_price',
            new_name='price',
        ),
    ]
