# Generated by Django 2.2.1 on 2019-05-17 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excercise', '0004_auto_20190516_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='turnament',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='turnament',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)]),
        ),
        migrations.AddField(
            model_name='usertur',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excercise.Turnament'),
        ),
        migrations.AddField(
            model_name='usertur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usertur',
            unique_together={('user', 'tournament')},
        ),
    ]
