# Generated by Django 2.2.1 on 2019-05-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excercise', '0006_remove_turnament_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newtur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newturnament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excercise.Turnament')),
            ],
        ),
    ]
