# Generated by Django 2.2.1 on 2019-05-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excercise', '0007_newtur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newtur',
        ),
    ]
