# Generated by Django 2.2.1 on 2019-05-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excercise', '0009_turnament_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnament',
            old_name='userid',
            new_name='user',
        ),
    ]
