# Generated by Django 2.2.1 on 2019-06-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercise', '0010_auto_20190523_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertur',
            name='is_favorite',
            field=models.IntegerField(choices=[(1, 'Zly'), (2, 'Kiepski'), (3, 'Sredni'), (4, 'Dobry'), (5, 'Bardzo Dobry')], default=0),
        ),
    ]
