# Generated by Django 2.2.1 on 2019-06-14 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excercise', '0013_auto_20190614_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertur',
            name='grade',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usertur',
            unique_together={('user', 'tournament', 'grade')},
        ),
        migrations.RemoveField(
            model_name='usertur',
            name='mark',
        ),
    ]
